# Program Behavior
profile=high-quality
reset-on-next-file=pause

# Video
vo=gpu-next
hwdec=auto-safe
#gpu-api=vulkan

# Subtitles
sub-auto=fuzzy

# Window
keep-open=yes
snap-window=yes
ontop=no

[hd-ready]
profile-desc=HD ready
profile-cond=get("current-gpu-context") ~= "d3d11" and (height == 720 or (width == 1280 and height < 720))
glsl-shader="~~/shaders/ravu-zoom-ar-r3.hook"

[hd-ready-d3d11]
profile-desc=HD ready (d3d11)
profile-cond=get("current-gpu-context") == "d3d11" and (height == 720 or (width == 1280 and height < 720))
vf=d3d11vpp=scale=2:scaling-mode=nvidia

[sdtv]
profile-desc=Standard-definition television
profile-cond=get("current-gpu-context") ~= "d3d11" and height <= 576
deinterlace=auto
glsl-shader="~~/shaders/ravu-zoom-ar-r3.hook"

[sdtv-d3d11]
profile-desc=Standard-definition television (d3d11)
profile-cond=get("current-gpu-context") == "d3d11" and height <= 576
deinterlace=auto
vf=d3d11vpp=scale=2:scaling-mode=nvidia
